{{- if .Values.serviceAccount.create }}
# ServiceAccount for the controller manager.
# Ref: https://github.com/achetronic/tunnel/blob/main/config/rbac/service_account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tunnel.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tunnel.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
